import 'package:store/presentation/ui/view_models/product_veiw_model.dart';

var productViewModelList = [
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
  ProductViewModel(name: 'capuccino ', compound: 'яйцо куриное, сахар-песок, сахарная пудра, сливки пастеризованные 38% из цельного коровьего молока, масло сливочное, миндальная пудра, творог, сметана, сыр сливочный, какао-порошок, шоколад натуральный.', price: 300, volume: 0.5, image: 'https://vkusnotochkamenu.ru/image/cachewebp/catalog/photo/53458915-kapuchino-600x600.webp',instock: 'в наличий'),
];
